### ISSUE TITLE
拉取https://registry.cn-zhangjiakou.aliyuncs.com 镜像报错/卡死

### ISSUE THREAD

**Issue by anjia0532** [dragonflyoss/Dragonfly2#1065]
通过  https://github.com/dragonflyoss/helm-charts/tree/main/charts/dragonfly 0.5.39 (docker 版本v2.0.2-rc.5) 安装到k8s集群(rke2 https://github.com/rancher/rke2/releases/tag/v1.21.7+rke2r2, Containerd 1.4.12)

`values.yaml`
```yaml
cdn:
  replicas: 1
  config:
    console: true
    verbose: true
containerRuntime:
  containerd:
    configPathDir: /var/lib/rancher/rke2/agent/etc/containerd
    enable: true
    injectConfigPath: false
    registries:
    - https://registry.cn-zhangjiakou.aliyuncs.com
dfdaemon:
  replicas: 1
  config:
    console: true
    proxy:
      registryMirror:
        url: https://registry.cn-zhangjiakou.aliyuncs.com
    verbose: true
manager:
  replicas: 1
  config:
    console: true
    verbose: true
scheduler:
  replicas: 1
  config:
    console: true
    verbose: true
mysql:
  enable: true
redis:
  enable: true
```

`config.toml`(`/var/lib/rancher/rke2/agent/etc/containerd/config.toml`)

```toml
[plugins.opt]
  path = "/var/lib/rancher/rke2/agent/containerd"

[plugins.cri]
  stream_server_address = "127.0.0.1"
  stream_server_port = "10010"
  enable_selinux = false
  sandbox_image = "index.docker.io/rancher/pause:3.6"

[plugins.cri.containerd]
  disable_snapshot_annotations = true
  snapshotter = "overlayfs"

[plugins.cri.containerd.runtimes.runc]
  runtime_type = "io.containerd.runc.v2"

[plugins.cri.registry.mirrors]

[plugins.cri.registry.mirrors."docker.io"]
  endpoint = ["https://xxx.mirror.aliyuncs.com"]

[plugins.cri.registry.mirrors."index.docker.io"]
  endpoint = ["https://xxx.mirror.aliyuncs.com"]

[plugins.cri.registry.mirrors."registry.cn-zhangjiakou.aliyuncs.com"]
  endpoint = ["http://127.0.0.1:65001", "https://registry.cn-zhangjiakou.aliyuncs.com"]
[plugins.cri.registry.configs."registry.cn-qingdao.aliyuncs.com".auth]
  username = "xxx"
  password = "xxx"
[plugins.cri.registry.configs."registry.cn-zhangjiakou.aliyuncs.com".auth]
  username = "xxxx"
  password = "xxxx"
```

提前将某个镜像从docker hub 转移到` registry.cn-zhangjiakou.aliyuncs.com`,注意将xxx替换成实际命名空间（https://cr.console.aliyun.com/cn-zhangjiakou/instance/namespaces 通过这里创建命名空间）

```bash
docker login registry.cn-zhangjiakou.aliyuncs.com
docker pull nacos/nacos-server:v2.0.4
docker tag nacos/nacos-server:v2.0.4 registry.cn-zhangjiakou.aliyuncs.com/xxx/nacos-server:v2.0.4
docker push registry.cn-zhangjiakou.aliyuncs.com/xxx/nacos-server:v2.0.4
```

第一次，是可以成功的,但是看daemon是报401，应该是走failback了，23秒下完
![1](https://user-images.githubusercontent.com/15098916/153842935-49d2a10b-980b-4f0e-a3cd-331e2473e131.png)

```bash
sudo /var/lib/rancher/rke2/bin/crictl --config=/var/lib/rancher/rke2/agent/etc/crictl.yaml pull registry.cn-zhangjiakou.aliyuncs.com/xxx/nacos-server:v2.0.4
Image is up to date for sha256:ea54f31c46e4720fb558829ffa41b2db6c2b6b6502221abee15fed2294bed664

real    0m39.154s
user    0m0.018s
sys     0m0.026s
```

清理掉本地缓存后，重新拉取，就死循环，也不报错，也不成功，一直僵死
```bash
sudo /var/lib/rancher/rke2/bin/crictl --config=/var/lib/rancher/rke2/agent/etc/crictl.yaml rmi --prune

sudo /var/lib/rancher/rke2/bin/crictl --config=/var/lib/rancher/rke2/agent/etc/crictl.yaml pull registry.cn-zhangjiakou.aliyuncs.com/xxx/nacos-server:v2.0.4
```

daemon就疯狂刷屏
![2](https://user-images.githubusercontent.com/15098916/153843204-8afd3feb-d83e-42ba-bc13-4944ff333e53.png)

cdn节点也疯狂刷屏
![3](https://user-images.githubusercontent.com/15098916/153843227-c6e68ae8-e4c8-48a0-951d-02a93883bd7f.png)

schedule 也是疯狂刷屏
![4](https://user-images.githubusercontent.com/15098916/153843255-d02a7d20-32a8-4ba4-8e7c-33ca600dd533.png)

![5](https://user-images.githubusercontent.com/15098916/153843292-8dbe2ffa-24cf-4430-8990-90a5568fd466.png)
