### ISSUE TITLE
dfdaemon pod log：Error: can not find available addresses

### ISSUE THREAD

**Issue by wgh9626** [dragonflyoss/Dragonfly2#1248]
helm chart version：0.5.52
kubectl get po -n dragonfly-system
NAME                                 READY   STATUS             RESTARTS        AGE
dragonfly-cdn-0                      1/1     Running            0               4h45m
dragonfly-cdn-1                      1/1     Running            0               4h35m
dragonfly-cdn-2                      1/1     Running            0               4h34m
dragonfly-dfdaemon-8fwfv             0/1     CrashLoopBackOff   1 (74s ago)     8s
dragonfly-dfdaemon-m7mh4             1/1     Running            6 (4h34m ago)   4h37m
dragonfly-dfdaemon-qlf6v             1/1     Running            6 (4h35m ago)   4h37m
dragonfly-manager-68d58794d7-dcbvj   1/1     Running            0               4h45m
dragonfly-manager-68d58794d7-wjq5j   1/1     Running            0               4h45m
dragonfly-manager-68d58794d7-wv2tm   1/1     Running            0               4h45m
dragonfly-mysql-0                    1/1     Running            0               4h45m
dragonfly-redis-master-0             1/1     Running            0               4h45m
dragonfly-redis-slave-0              1/1     Running            0               4h45m
dragonfly-redis-slave-1              1/1     Running            0               4h44m
dragonfly-scheduler-0                1/1     Running            0               4h45m
dragonfly-scheduler-1                1/1     Running            0               4h32m
dragonfly-scheduler-2                1/1     Running            0               4h32m

kubectl logs -f dragonfly-dfdaemon-8fwfv -n dragonfly-system
Error: can not find available addresses

How can I solve this problem？

**Comment by gaius-qi** [comment]
Do all dfdaemons cannot find available addresses?

**Comment by rookiegogo** [comment]
> 

same problem
all dfdaemons cannot find available addresses
```shell
$ kubectl -n dragonfly-system logs -f dragonfly-dfdaemon-kfhxs
Error: can not find available addresses
```

helm chart version：0.5.52
k8s version: 1.18.6
helm version: v3.8.2
kubeadm yaml: 
```yaml
apiVersion: kubeadm.k8s.io/v1beta2
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: abcdef.0123456789abcdef
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 10.x.x.x
  bindPort: 6443
nodeRegistration:
  criSocket: /var/run/dockershim.sock
  name: 10.x.x.x
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
---
apiServer:
  timeoutForControlPlane: 4m0s
apiVersion: kubeadm.k8s.io/v1beta2
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controlPlaneEndpoint: "10.x.x.x:6443"
#controllerManager: {}
#scheduler: {}
dns:
  type: CoreDNS
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: harbor.xxxxx.com
kind: ClusterConfiguration
kubernetesVersion: v1.18.6
networking:
  dnsDomain: cluster.local
  podSubnet: "172.14.0.0/16" 
  serviceSubnet: "172.15.0.0/16"
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: systemd
clusterDNS: ["172.15.0.10"]
clusterDomain: cluster.local
maxPods: 220
evictionHard: {"nodefs.available": "20%", "imagefs.available": "15%"}
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: ipvs
featureGates:
  SupportIPVSProxyMode: true
```
