### ISSUE TITLE
Dragonfly and nydus are integrated via mirror

### ISSUE THREAD

**Issue by gaius-qi** [dragonflyoss/Dragonfly2#1678]

**Comment by imeoer** [comment]
@sctb512 @raoxiang1996 We can reference the issue once the PR about mirror support is ready on nydus side, some docs should be published.

**Comment by gaius-qi** [comment]
Test: https://hackmd.io/2g_NiyapQJOavVKPu4NNfw?view

**Comment by gaius-qi** [comment]
# Install Test Environment:

## Install Dragonfly

**Create Kind Cluster**

Kind Config `config-peer.yaml`:
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: dual
nodes:
- role: control-plane
  image: kindest/node:v1.23.4@sha256:0e34f0d0fd448aa2f2819cfd74e99fe5793a6e4938b328f657c8e3f81ee0dfb9
- role: worker
  image: kindest/node:v1.23.4@sha256:0e34f0d0fd448aa2f2819cfd74e99fe5793a6e4938b328f657c8e3f81ee0dfb9
  extraPortMappings:
  - containerPort: 30950
    hostPort: 65001
- role: worker
  image: kindest/node:v1.23.4@sha256:0e34f0d0fd448aa2f2819cfd74e99fe5793a6e4938b328f657c8e3f81ee0dfb9
- role: worker
  image: kindest/node:v1.23.4@sha256:0e34f0d0fd448aa2f2819cfd74e99fe5793a6e4938b328f657c8e3f81ee0dfb9
```

```shell
kind create cluster --config ./config-peer.yaml
```
