### ISSUE TITLE
dfdaemon registryMirror with header

### ISSUE THREAD

**Issue by supakornbabe** [dragonflyoss/Dragonfly2#1953]
### Feature request:

As we are using dragonfly to cache our harbor registry and after we upgrade harbor to v2.3.0 we faced the issue https://github.com/goharbor/harbor/issues/15178 so we have to do the workaround by having the proxy service that use to add the header `Authorization: none` so it should be great to have this function directly from dragonfly so we can deprecate our workaround

### Use case:

dfdaemon config is added with registryMirror.header config
```
dfdaemon:
  config:
    proxy:
      registryMirror:
        url: https://harbor.test.io
        header: "Authorization: none"
```
