### ISSUE TITLE
添加 caCert 并不能解决自签发证书问题.

### ISSUE THREAD

**Issue by chisaato** [dragonflyoss/Dragonfly2#2506]
以 upload 为例,做如下配置

```yaml
upload:
  rateLimit: 1024Mi
  security:
    insecure: false
    caCert: ca.crt
    cert: df-seed-peer/cache/certs/dfdaemon/0.0.0.0.crt
    key: df-seed-peer/cache/certs/dfdaemon/0.0.0.0.key
    tlsVerify: false
  tcpListen:
    port: 65002
```

当其他Peer从这里下载的时候,日志里就会出现 `tls: failed to verify certificate: x509: certificate signed by unknown authority`
经过一番排查,在 

https://github.com/dragonflyoss/Dragonfly2/blob/07366174b5f48002f234445713132d768e67345c/client/daemon/peer/piece_downloader.go#L156C3

```go
if caCertPool != nil {
  pd.scheme = "https"
  defaultTransport.(*http.Transport).TLSClientConfig = &tls.Config{RootCAs: caCertPool}
}
```

这里仅仅是将证书添加到了 ClientCA 中,我猜测这也许是用于TLS双向认证用的. 但是他不能解决使用自签发证书时请求的握手.

![image](https://github.com/dragonflyoss/Dragonfly2/assets/17796830/d47194a9-3968-420a-8c79-59cfd1cff480)

可以看到这里 RootCA 是空的

可以考虑顺带将 caCert 也加入到 RootCA 中以完成 TLS 传输 (而不仅仅是 TLS 身份验证)
