### ISSUE TITLE
scheduler sometimes freezes

### ISSUE THREAD

**Issue by rrgadeev** [dragonflyoss/Dragonfly2#2832]
symptoms:
docker pull in the long wait

scheduler there is a constant error in the log:
core.log
`{"level":"info","ts":"2023-10-27 07:56:00.040","caller":"resource/peer.go:312","msg":"peer state is Leave","hostID":"1bd66addc5e1563731c02006ce950468bfae8bdb4961d11ba7ca03b9dca1eb1e","taskID":"079d2817b15a9ad5f2c19a78f81f96bc626e90d6cf904a1bcf5ea1e1c5d7d467","peerID":"172.16.23.96-551-8dfdf4d1-b9b0-48c1-9baa-c567e6a74347"}`

restarting scheduler helps

docker image:
dragonflyoss/scheduler:v2.1.7

workaround:
```
    healthcheck:
      test: ["CMD-SHELL", "/bin/grpc_health_probe -addr=:8002 && tail  /var/log/dragonfly/scheduler/core.log |grep -q -v Leave || exit 1"]
      interval: 1s
      timeout: 2s
      retries: 30
```
