### ISSUE TITLE
When I have completed the installation of the Dragonfly software, I did not find task logs in the Dfdaemon logs.

### ISSUE THREAD

**Issue by nicefuture2016** [dragonflyoss/Dragonfly2#2885]
**k8s version: v1.27.2
helm version:3.12.2
runtime: containerd
config.toml version: 2
dragonfly version:v2.1.20**

**it`s my containerd config.toml**

![config](https://github.com/dragonflyoss/Dragonfly2/assets/18341440/c71a40f4-b406-4988-b3b3-2db61ba01b4a)

**my helm value**
![helm](https://github.com/dragonflyoss/Dragonfly2/assets/18341440/5f66a61a-abed-42ec-9418-4a4a856c0e86)

**All compoment running**

![pod](https://github.com/dragonflyoss/Dragonfly2/assets/18341440/cfaa5e5c-b002-49d4-bac5-7b00c4bc50e2)

**config.toml added new line when dragonfly  installed, and weird all pods did not restart when  containerd restart**

![last](https://github.com/dragonflyoss/Dragonfly2/assets/18341440/34ea2c5e-c28e-4272-b243-4d55f08bf653)

**dfdaemon log**

![log](https://github.com/dragonflyoss/Dragonfly2/assets/18341440/e18d5ea7-46e6-430b-ac30-cfb0cccf0f4b)

![log1](https://github.com/dragonflyoss/Dragonfly2/assets/18341440/3ee5c118-9015-429c-b8fb-771e48385425)

[Uploading core.log…]()

**Comment by gaius-qi** [comment]
@nicefuture2016 Please give me the charts configuration file so I can reproduce.

**Comment by nicefuture2016** [comment]
> @nicefuture2016 Please give me the charts configuration file so I can reproduce.

hello,this is my charts

```yml
scheduler:
  image: dragonflyoss/scheduler
  tag: v2.1.20
  config:
    manager:
      schedulerClusterID: 4

seedPeer:
  image: dragonflyoss/dfdaemon
  tag: v2.1.20
  persistence: 
    enable: true
    storageClass: nfs-storage 
  config:
    scheduler:
      manager:
        seedPeer:
          clusterID: 4

dfdaemon:
  image: dragonflyoss/dfdaemon
  tag: v2.1.20
  config:
    host:
      idc: shangrao

manager:
  enable: false

externalManager:
  enable: true
  host: dragonfly.manage.com    # set in coredns
  restPort: 8689
  grpcPort: 65003

redis:
  enable: false

externalRedis:
  addrs:
    - xxx.xxx.xxx.xxx:8688
  password: xxxxxxxxxx

mysql:
  enable: false

containerRuntime:
  containerd:
    enable: true
      #injectConfigPath: true
    registries:
      - 'https://harbor-core.xxx.cn'
```
