### ISSUE TITLE
dragonfly manager config tls error: 500 Internal Server Error 

### ISSUE THREAD

**Issue by mansoncui** [dragonflyoss/Dragonfly2#3157]
### Bug report:

helm install dragonfly

Error Info :
2024-04-01T09:15:03Z [INFO] [/pkg/p2p/preheat/job.go:93]: Preheating image 'dragonfly/bitnami-shell:11-debian-11-r72@sha256:5098aa7e6360c5ee5e38152e49e03faaee8a57d5a8dcd94ea00c5490dbe87858' to the target preheat provider: dragonfly Dragonfly:http://10.215.1.168:8080
2024-04-01T09:15:03Z [INFO] [/pkg/p2p/preheat/job.go:120]: Get preheat provider driver: dragonfly
2024-04-01T09:15:03Z [INFO] [/pkg/p2p/preheat/job.go:134]: Check health of preheat provider instance: Healthy
2024-04-01T09:15:03Z [ERROR] [/pkg/p2p/preheat/job.go:75]: POST 'http://10.215.1.168:8080/preheats' error: 500 Internal Server Error {"message":"Get \"https://harbor-xx.xx.xxx.xx/v2/\": tls: failed to verify certificate: x509: certificate signed by unknown authority"}

Tls has been enabled in the manager service ，The configuration is as follows：
manager:
  replicas: 1
  metrics:
    enable: true
  config:
    verbose: true
    pprofPort: 18066
    job:
      syncPeers:
        timeout: 10m
      preheat:
        registryTimeout: 1m
      tls:
        # caCert is the CA certificate for preheat tls handshake, it can be path or PEM format string.
        caCert: '-----BEGIN CERTIFICATE-----
xxxxxxxx
-----END CERTIFICATE-----'

It is possible to request harbor 443 through local curl, as shown below:
<img width="952" alt="dragonfly" src="https://github.com/dragonflyoss/Dragonfly2/assets/29750171/9f87c8ee-60b4-4397-98d7-3eac2269d409">

### Environment:
- Dragonfly version: 2.1.30
- OS: ubuntu 18.04
- Kernel : 5.4.193-0504193-generic
- Others: chat version 1.1.26

**Comment by gaius-qi** [comment]
Please show your configuration file.

**Comment by mansoncui** [comment]
<img width="707" alt="image" src="https://github.com/dragonflyoss/Dragonfly2/assets/29750171/ff28eea4-9896-4b85-a00a-5446818d6730">

**Comment by gaius-qi** [comment]
https://d7y.io/docs/next/reference/configuration/manager

```yaml
# Job configuration.
job:
  # Sync peers configuration.
  syncPeers:
    # Interval is the interval for syncing all peers information from the scheduler and
    # display peers information in the manager console.
    interval: 24h
    # Timeout is the timeout for syncing peers information from the single scheduler.
    timeout: 10m
  # Preheat configuration.
  preheat:
    # registryTimeout is the timeout for requesting registry to get token and manifest.
    registryTimeout: 1m
    tls:
      # caCert is the CA certificate for preheat tls handshake, it can be path or PEM format string.
      caCert: ''
```
