### ISSUE TITLE
httpserver addr by read config init

### ISSUE THREAD

**Issue by lengrongfu** [dragonflyoss/Dragonfly2#351]
### Feature request:

HTTP service listening port cannot use the custom configuration

### Use case:

```yaml
server:
  ip: ""
  port: 8004
```
