### ISSUE TITLE
dragonfly client seems to not utilize huggingface caches 

### ISSUE THREAD

**Issue by Yeosangho** [dragonflyoss/Dragonfly2#3636]
### Bug report:

Hello, I am a first-time user of Dragonfly.
We are planning to use Dragonfly to set up a proxy service for Hugging Face.
Based on the manual content, I succeeded in fetching Hugging Face repos through the Dragonfly client. 

However, after deleting the Hugging Face repository cache locally (rm -rf ~/.cache/hugginface) and re-running the test code, I confirmed that the download speed is almost the same as the initial repository download. The strange thing is that on the Dragonfly client (i.e., peer), a cache for the repository is created in /var/lib/dragonfly/contents/task with each download. 

So, I wonder why it does not use the cache of repo.

### How to reproduce it:
Cluster setting : I followed huggingface integration manual (https://d7y.io/docs/next/operations/integrations/hugging-face/)

Helm values and codes : 

values.yaml
```
manager:
  image:
    repository: dragonflyoss/manager
    tag: latest
  metrics:
    enable: true
  config:
    verbose: true
    pprofPort: 18066

scheduler:
  image:
    repository: dragonflyoss/scheduler
    tag: latest
  metrics:
    enable: true
  config:
    verbose: true
    pprofPort: 18066

seedClient:
  replicas: 1
  hostNetwork: false
  image:
    repository: dragonflyoss/client
    tag: latest
  metrics:
    enable: true
  config:
    verbose: true
    seedPeer:
      # -- enable indicates whether enable seed peer.
      enable: true
    download:
      server:
        # -- socketPath is the unix socket path for dfdaemon GRPC service.
        socketPath: /var/run/dragonfly/dfdaemon.sock
      # -- rateLimit is the default rate limit of the download speed in GiB/Mib/Kib per second, default is 50GiB/s.
      rateLimit: 50GiB
      # --  pieceTimeout is the timeout for downloading a piece from source.
      pieceTimeout: 30s
      # -- concurrentPieceCount is the number of concurrent pieces to download.
      concurrentPieceCount: 15
    proxy:
      server:
        port: 4001
      registryMirror:
        addr: http://cdn-lfs-us-1.hf.co
      rules:
        - regex: ".*"
          useTLS: true


client:
  enabled: true
  image:
    repository: dragonflyoss/client
    tag: latest
  hostNetwork: true
  metrics:
    enable: true

  config:
    verbose: true
    seedPeer:
      # -- enable indicates whether enable seed peer.
      enable: true
    download:
      server:
        # -- socketPath is the unix socket path for dfdaemon GRPC service.
        socketPath: /var/run/dragonfly/dfdaemon.sock
      # -- rateLimit is the default rate limit of the download speed in GiB/Mib/Kib per second, default is 50GiB/s.
      rateLimit: 50GiB
      # --  pieceTimeout is the timeout for downloading a piece from source.
      pieceTimeout: 30s
      # -- concurrentPieceCount is the number of concurrent pieces to download.
      concurrentPieceCount: 15
    proxy:
      server:
        port: 4001
      registryMirror:
        addr: http://cdn-lfs-us-1.hf.co
      rules:
        - regex: ".*"
          useTLS: true

```
hf_download.py (I changed CDN address due to the example repo resides in another CDN in huggingface. 

```
import requests
from requests.adapters import HTTPAdapter
from urllib.parse import urlparse
from huggingface_hub import hf_hub_download
from huggingface_hub import configure_http_backend
import urllib3
import logging

logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger(__name__)


urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

class DragonflyAdapter(HTTPAdapter):
    def get_connection(self, url, proxies=None):
        # Change the schema of the LFS request to download large files from https:// to http://,
        # so that Dragonfly HTTP proxy can be used.
        if url.startswith('https://cdn-lfs-us-1.hf.co'):
            url = url.replace('https://', 'http://')
        return super().get_connection(url, proxies)
        
    def send(self, request, **kwargs):  #get_connection does not convert the https to http, thus I override send method also.
        if request.url.startswith('https://'):
            #if 'cdn-lfs.hf.co' in request.url:
            if 'cdn-lfs-us-1.hf.co' in request.url: #this url is CDN of current target huggingface repo.
                logger.debug(f"Original URL: {request.url}")
                request.url = request.url.replace('https://', 'http://')
                logger.debug(f"Converted URL: {request.url}")
        return super().send(request, **kwargs)

    def add_headers(self, request, **kwargs):
        super().add_headers(request, **kwargs)
        if request.url.find('example.com') != -1:
            request.headers["X-Dragonfly-Registry"] = 'https://example.com'

def backend_factory() -> requests.Session:
    session = requests.Session()
    session.mount('http://', DragonflyAdapter())
    session.mount('https://', DragonflyAdapter())
    session.proxies = {
        'http': 'http://192.168.2.41:4001',
        #'https': 'http://192.168.2.41:4001' # I disabled the https case, because https is converted to http by overrided send method. 
    }
    session.verify = False
    return session

configure_http_backend(backend_factory=backend_factory)

try:
    hf_hub_download(
        repo_id="OuteAI/OuteTTS-0.1-350M",
        filename="model.safetensors",
        local_files_only=False
    )
except Exception as e:
    print(f"Download error: {e}")


```

And to connect with client, we apply the service spec for kind cluster. 

```
apiVersion: v1
kind: Service
metadata:
  name: peer
  namespace: dragonfly-system
spec:
  type: NodePort
  ports:
    - name: http-4001
      nodePort: 30950
      port: 4001
  selector:
    app: dragonfly
    component: client
    release: dragonfly

```

Lastly, we run the code with increasing read time to avoid read time out in huggingface file download.

```
HF_HUB_DOWNLOAD_TIMEOUT=1000 python hf_download.py 
```

#### Test results.

hf_hub_download without proxy : 65 seconds (I deleted session proxies in the code)
<img width="1133" alt="image" src="https://github.com/user-attachments/assets/64e5b20a-e0db-4979-873e-c641afe52b5c">

hf_hub_download with proxy , first trial(i.e. supposed to not use cache), : 41 seconds
<img width="1130" alt="image" src="https://github.com/user-attachments/assets/eb592e60-d1ad-4cc8-9795-2af1677fc432">

After rm -rf ~/.cache/hugginface,...
hf_hub_download with proxy , second trial(i.e., it supposed to be use cache) : 40 seconds
<img width="1130" alt="image" src="https://github.com/user-attachments/assets/8a3e6950-15e0-44a3-a1bc-4f5a0cc88fec">

In addition, I tested additional cases with  **concurrentPieceCount as 1** in both seedclient and client to check the impact of cache only.

hf_hub_download with proxy, first trial(i.e. supposed to not use cache), concurrentPieceCount 1 : 231 seconds
<img width="1129" alt="image" src="https://github.com/user-attachments/assets/de37e393-1b46-4ece-b595-87d92b9201cc">

After rm -rf ~/.cache/hugginface ,...
hf_hub_download with proxy, second trial,(i.e., supposed to use cache), concurrentPieceCount 1 : 202-236 seconds

<img width="1122" alt="image" src="https://github.com/user-attachments/assets/6f379cbf-2e81-4674-ade1-d01ea23f1f67">

<img width="1126" alt="image" src="https://github.com/user-attachments/assets/3e110821-f96c-4caa-8091-ed0e501433b6">

I'll looking forward your answer!!! 👍 

### Environment:

- Dragonfly version:  I used latest images of dragonfly2, but I don't know how can I get the version of dragonfly.
- OS:  Ubuntu 22.04.3 LTS
- Kernel (e.g. `uname -a`): Linux vnode1.pnode3.idc1.ten1010.io 5.15.0-86-generic #96-Ubuntu SMP Wed Sep 20 08:23:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- Others:
