### ISSUE TITLE
harbbor preheat can not connect dragonfly2

### ISSUE THREAD

**Issue by MouseSun846** [dragonflyoss/Dragonfly2#3651]
![image](https://github.com/user-attachments/assets/72bb63de-5662-4427-8740-dc4e494360aa)
![image](https://github.com/user-attachments/assets/cad8aca9-9e52-4779-8d58-19fde53ca1e9)
![image](https://github.com/user-attachments/assets/54251980-0ca7-4879-9cfb-473ed4b1e6db)

dragonfly2 has deployed,but harbbor preheat can not connect dragonfly2

harbor log
```
2024-11-14T03:39:58Z [ERROR] [/pkg/p2p/preheat/provider/client/http_client.go:75]: Get http://10.0.102.61:18080/_ping with cred=&{OAUTH map[]}, params=map[], options=map[]: no credential data provided
2024-11-14T03:39:58Z [ERROR] [/lib/http/error.go:57]: {"errors":[{"code":"UNKNOWN","message":"unknown: no credential data provided"}]} 
```

bu config manager insecureSkipVerify
```
      preheat:
        # -- registryTimeout is the timeout for requesting registry to get token and manifest.
        registryTimeout: 1m
        tls:
          # -- insecureSkipVerify controls whether a client verifies the
          # server's certificate chain and hostname.
          insecureSkipVerify: true
        # # caCert is the CA certificate for preheat tls handshake, it can be path or PEM format string.
        # caCert: ''
```
