### ISSUE TITLE
cannot find cdn-host

### ISSUE THREAD

**Issue by ish-xyz** [dragonflyoss/Dragonfly2#663]
### Bug report:
Hi,

I'm deploying dragonfly with only scheduler, cdn and dfdaemons. I'm currently experiencing the following error:

```
2021-09-21T08:58:28.856Z        ERROR   cdn/manager.go:184      cannot find cdn host cdn-0-8003_CDN
d7y.io/dragonfly/v2/scheduler/supervisor/cdn.(*manager).initCdnPeer
        /go/src/d7y.io/dragonfly/v2/scheduler/supervisor/cdn/manager.go:184
d7y.io/dragonfly/v2/scheduler/supervisor/cdn.(*manager).receivePiece
        /go/src/d7y.io/dragonfly/v2/scheduler/supervisor/cdn/manager.go:143
d7y.io/dragonfly/v2/scheduler/supervisor/cdn.(*manager).StartSeedTask
        /go/src/d7y.io/dragonfly/v2/scheduler/supervisor/cdn/manager.go:110
d7y.io/dragonfly/v2/scheduler/core.(*SchedulerService).GetOrCreateTask.func1
        /go/src/d7y.io/dragonfly/v2/scheduler/core/service.go:280
```
Dragonfly is runnig on top of a k8s cluster with the following details:

dfdaemon as daemonset
scheduler as statefulset
cdn as statefulset

I've used the deployment used here for the CDN -> https://github.com/dragonflyoss/Dragonfly2/blob/main/deploy/kustomize/single-cluster-native/bases/cdn/statefulset.yaml

The cdn config is:

```
    base:
      # listenPort is the port cdn server listens on.
      # default: 8003
      listenPort: 8003
      advertiseIP: __MY_POD_IP__

      # DownloadPort is the port for download files from cdn.
      # And you should start a file server firstly which listens on the download port.
      # default: 8001
      downloadPort: 8001

      # SystemReservedBandwidth is the network bandwidth reserved for system software.
      # default: 20 MB, in format of G(B)/g/M(B)/m/K(B)/k/B, pure number will also be parsed as Byte.
      systemReservedBandwidth: 20M

      # MaxBandwidth is the network bandwidth that cdn can use.
      # default: 200 MB, in format of G(B)/g/M(B)/m/K(B)/k/B, pure number will also be parsed as Byte.
      maxBandwidth: 1024M

      # Whether to enable profiler
      # default: false
      enableProfiler: false

      # FailAccessInterval is the interval time after failed to access the URL.
      # If a task failed to be downloaded from the source, it will not be retried in the time since the last failure.
      # default: 3m
      failAccessInterval: 3m

      # GCInitialDelay is the delay time from the start to the first GC execution.
      # default: 6s
      gcInitialDelay: 6s

      # GCMetaInterval is the interval time to execute GC meta.
      # default: 2m0s
      gcMetaInterval: 2m

      # gcStorageInterval is the interval time to execute GC storage.
      # default: 15s
      gcStorageInterval: 15s

      # TaskExpireTime when a task is not accessed within the taskExpireTime,
      # and it will be treated to be expired.
      # default: 3m0s
      taskExpireTime: 15m

      # StoragePattern is the pattern of storage policy, [disk/hybrid]
      storagePattern: disk

      # Console shows log on console
      console: true

    plugins:
      storageDriver:
      - name: disk
        enable: true
        config:
          baseDir: /var/lib/dragonfly/cdn
      storageManager:
      - name: disk
        enable: true
        config:
          gcInitialDelay: 5s
          gcInterval: 15s
          driverConfigs:
            disk:
              gcConfig:
                youngGCThreshold: 100G
                fullGCThreshold: 5G
                cleanRatio: 1
                intervalThreshold: 2h
```

The scheduler config looks like:
```
  scheduler.yaml: |
    console: true
    verbose: true
    server:
      ip: __MY_POD_IP__
      host: __MY__HOSTNAME__
      port: 8002
    scheduler:
      gc:
        peerGCInterval: 3m0s
        peerTTL: 15m0s
        peerTTI: 10m0s
        taskGCInterval: 1m0s
        taskTTL: 15m0s
        taskTTI: 5m0s
    worker:
      workerNum: 10
      workerJobPoolSize: 10000
      senderNum: 20
      senderJobPoolSize: 10000
    dynconfig:
      cdnDirPath: /opt/dragonfly/scheduler-cdn
   ```

this is the dfdaemon config:

```
  config.yaml: |
    # daemon alive time, when sets 0s, daemon will not auto exit
    # it is useful for longtime running
    aliveTime: 0s
    console: true
    # when enable, pprof will be enabled
    verbose: false
    gcInterval: 1m0s
    dataDir: /var/lib/dragonfly
    workHome: /var/lib/dragonfly
    keepStorage: false

    scheduler:
      scheduleTimeout: 30s
      # when true, only scheduler says back source, daemon can back source
      disableAutoBackSource: true
      netAddrs:
        {{- $values  := .Values -}}
        {{ $replicas := .Values.dragonfly.scheduler.replicas | int }}
        {{ range until $replicas -}}
        - type: tcp
          addr: scheduler-{{ . }}.{{ $values.dragonfly.scheduler.serviceName }}:8002
        {{end}}

    # current host info used for scheduler
    host:
      listenIP: 0.0.0.0
      advertiseIP: 0.0.0.0
      location: {{ .Values.clusterName }}
      idc: {{ .Values.datacenter }}
      securityDomain: {{ .Values.datacenter }}
      netTopology: ""

    # download service option
    download:
      totalRateLimit: 900Mi
      perPeerRateLimit: 900Mi
      pieceDownloadTimeout: 60s
      downloadGRPC:
        # security option
        security:
          insecure: true #TODO
          cacert: ""
          cert: ""
          key: ""
          tlsConfig: null
        unixListen:
          socket: /var/run/dfdaemon.sock
      # peer grpc option
      # peer grpc service send pieces info to other peers
      peerGRPC:
        security:
          insecure: true
          cacert: ""
          cert: ""
          key: ""
        tcpListen:
          # listen address
          listen: 0.0.0.0
          port: 65000

    # upload service option
    upload:
      # upload limit per second
      rateLimit: 900Mi
      security:
        insecure: true
        cacert: ""
        cert: ""
        key: ""
      tcpListen:
        # listen address
        listen: 0.0.0.0
        port: 65002

    # peer task storage option
    storage:
      # task data expire time
      # when there is no access to a task data, this task will be gc.
      taskExpireTime: 15m0s
      # storage strategy when process task data
      # io.d7y.storage.v2.simple : download file to data directory first, then copy to output path, this is default action
      #                           the download file in date directory will be the peer data for uploading to other peers
      # io.d7y.storage.v2.advance: download file directly to output path with postfix, hard link to final output,
      #                            avoid copy to output path, fast than simple strategy, but:
      #                            the output file with postfix will be the peer data for uploading to other peers
      #                            when user delete or change this file, this peer data will be corrupted
      # default is io.d7y.storage.v2.advance
      strategy: io.d7y.storage.v2.advance
      diskGCThreshold: 50Gi
      # set to ture for reusing underlying storage for same task id
      multiplex: true

    proxy:
      defaultFilter: "Expires&Signature"
      security:
        insecure: true
        cacert: ""
        cert: ""
        key: ""
      tcpListen:
        namespace: ""
        listen: 0.0.0.0
        port: 65001

      registryMirror:
        url: http://{{ .Values.dragonfly.backend.serviceName }}:8080
        insecure: true
        certs: []
        direct: false
```

Can anyone help me please?
