### ISSUE TITLE
Dragonfly performance issues, misconfiguration? (help wanted)

### ISSUE THREAD

**Issue by ish-xyz** [dragonflyoss/Dragonfly2#692]
I'm trying to run Dragonfly on a small cluster with 6 nodes and I'm noticing some performance issues when I run 1000 docker pulls at the same time.
I'm using a tool that I developed to perform the docker pulls it just triggers multiple go routines and each go routine will ask for the docker image manifest and download the layers.
If I trigger 100/200 pulls in parallel everything it's fine, as soon as I increase to 800/1000 I start noticing 500 errors in the requests that the tool does.

Currently I have 3 schedulers, 6 dfdaemons (one for each node), 1 cdn (deployed as statefulset).
Each node in the cluster have 65GB ram and there's a 1GB/s connectivity between nodes.

The configurations used are the following:

scheduler:
```
 scheduler:
    workerNum: 1000000
    backSourceCount: 3
    accessWindow: 3m
    candidateParentCount: 100
    cdnLoad: 10000
    clientLoad: 1000

  dynconfig:
      cdnDirPath: /opt/dragonfly/scheduler-cdn

  disableCDN: false
  console: true
  verbose: false
```

cdn:
```
    base:
      listenPort: 8003
      downloadPort: 8001
      systemReservedBandwidth: 20M
      maxBandwidth: 1024M
      enableProfiler: false
      failAccessInterval: 3m
      gcInitialDelay: 6s
      gcMetaInterval: 2m
      gcStorageInterval: 15s
      taskExpireTime: 3m
      storagePattern: disk
      console: true
    plugins:
      storageDriver:
      - name: disk
        enable: true
        config:
          baseDir: /var/lib/dragonfly/cdn
      storageManager:
      - name: disk
        enable: true
        config:
          gcInitialDelay: 5s
          gcInterval: 15s
          driverConfigs:
            disk:
              gcConfig:
                youngGCThreshold: 100G
                fullGCThreshold: 5G
                cleanRatio: 1
                intervalThreshold: 2h
```

dfdaemon:
```
   # daemon alive time, when sets 0s, daemon will not auto exit
    # it is useful for longtime running
    aliveTime: 0s
    console: true
    # when enable, pprof will be enabled
    verbose: false
    gcInterval: 1m0s
    dataDir: /var/lib/dragonfly
    workHome: /var/lib/dragonfly
    keepStorage: false

    scheduler:
      scheduleTimeout: 30s
      # when true, only scheduler says back source, daemon can back source
      disableAutoBackSource: true
      netAddrs:
        - type: tcp
          addr: scheduler-0:8002
        - type: tcp
          addr: scheduler-1:8002
        - type: tcp
          addr: scheduler-2:8002


    # current host info used for scheduler
    host:
      listenIP: 0.0.0.0
      advertiseIP: 0.0.0.0
      location: {{ .Values.clusterName }}
      idc: {{ .Values.datacenter }}
      securityDomain: {{ .Values.datacenter }}
      netTopology: ""

    # download service option
    download:
      totalRateLimit: 500Mi
      perPeerRateLimit: 250Mi
      pieceDownloadTimeout: 60s
      downloadGRPC:
        # security option
        security:
          insecure: true #TODO
          cacert: ""
          cert: ""
          key: ""
          tlsConfig: null
        unixListen:
          socket: /var/run/dfdaemon.sock
      # peer grpc option
      # peer grpc service send pieces info to other peers
      peerGRPC:
        security:
          insecure: true
          cacert: ""
          cert: ""
          key: ""
        tcpListen:
          # listen address
          listen: 0.0.0.0
          port: 65000

    # upload service option
    upload:
      # upload limit per second
      rateLimit: 500Mi
      security:
        insecure: true
        cacert: ""
        cert: ""
        key: ""
      tcpListen:
        # listen address
        listen: 0.0.0.0
        port: 65002

    # peer task storage option
    storage:
      # task data expire time
      # when there is no access to a task data, this task will be gc.
      taskExpireTime: 3m0s
      strategy: io.d7y.storage.v2.advance
      diskGCThreshold: {{ .Values.dragonfly.dfdaemon.diskGCThreshold }} #50Gi by default
      # set to ture for reusing underlying storage for same task id
      multiplex: true

    proxy:
      defaultFilter: "Expires&Signature"
      security:
        insecure: true
        cacert: ""
        cert: ""
        key: ""
      tcpListen:
        namespace: ""
        listen: 0.0.0.0
        port: 65001

      registryMirror:
        url: http://registry:8080
        insecure: true
        certs: []
        direct: false
```

When I notice the error (500 error) the logs in the scheduler says:

```
2021-09-27T13:59:13.548Z        DEBUG   basic/basic_scheduler.go:264    finish schedule parent flow, select num 0 candidates parents, current task tree node count 1, back source peers: [10.1.75.159-1-6ef75e8a-8edc-48bd-bdba-d0cb8d125cfb 10.1.247.1-1-ff71e57e-3a2d-4684-9e66-0fa0ff1dc323 10.1.160.193-1-2efed1a1-1cf3-45d0-b0d4-b618e5e5c9b4 10.1.160.193-1-d925f7ee-d5c9-4434-b786-48cfaa9d3fb3 10.1.0.94-1-11f6b3c9-0f23-4173-9d55-4ad7455bd64f 10.1.160.193-1-05c821f3-4ed0-4e32-9a5c-b569e5d402d1 10.1.247.1-1-19cd5d9f-535e-4fc2-b4a4-b796bededf66 10.1.75.159-1-73c47102-3ca5-48a7-a9a2-fccdc83eb47d 10.1.160.193-1-7993e2b0-4856-45b2-8253-15247bddfc99 10.1.247.1-1-dfe03494-df37-4d6f-a961-1350472b220b 10.1.210.56-1-4e04fc36-a545-4bca-a38f-cea685ac0b72 10.1.48.13-1-11c84096-a2e1-4ebc-a387-b4919b2b09ef 10.1.75.159-1-0c9f3acc-f95a-4d71-b443-c16071a759dc  .....(VERY LONG LIST) ........
```

```
xx@xx:~/xx/xx$ k logs scheduler-0 | grep ERROR
2021-09-27T13:59:22.451Z        ERROR   core/events.go:94       reScheduleParent: failed to schedule parent to peer 10.1.160.193-1-a19c2466-cfb6-4e17-8cab-a8a45d98456d, reschedule it later
2021-09-27T13:59:22.468Z        ERROR   core/events.go:94       reScheduleParent: failed to schedule parent to peer 10.1.160.193-1-7aa1054a-4518-48c9-96cc-42de32901d65, reschedule it later
2021-09-27T13:59:22.473Z        ERROR   core/events.go:94       reScheduleParent: failed to schedule parent to peer 10.1.0.94-1-81e52445-af49-4764-b38b-984a43180d38, reschedule it later
2021-09-27T13:59:22.505Z        ERROR   core/events.go:94       reScheduleParent: failed to schedule parent to peer 10.1.75.159-1-ff2fc174-6460-4808-bcab-f7fc291d5f41, reschedule it later
2021-09-27T13:59:23.354Z        ERROR   core/events.go:94       reScheduleParent: failed to schedule parent to peer 10.1.48.13-1-b7e7bcb7-3678-4057-809d-7fd4fe4c5d28, reschedule it later
2021-09-27T13:59:23.418Z        ERROR   core/events.go:94       reScheduleParent: failed to schedule parent to peer 10.1.75.159-1-a5d4a2ba-7d9b-492c-b8cd-837462e5ebca, reschedule it later
(VERY LONG LIST)
```

What am I missing? Can you spot any clear error @jim3ma?

I've disabled autobacksource on purpose as I don't want requests going to the upstream from the dfdaemons.
