### ISSUE TITLE
Image always comes from CDN and not peer 

### ISSUE THREAD

**Issue by mohafarooq** [dragonflyoss/Dragonfly2#707]
### Bug report:
I see that all the time the image gets downloaded from CDN and not from the peer. What is the algorithm used to choose between CDN and the peer? I would prefer the image pieces to come from multiple peers as opposed to a single CDN. 

### Environment:
- Dragonfly version: v2.0.1-alpha.0
- OS: 
- Kernel (e.g. `uname -a`): 4.12.14
- Others:

**Comment by ish-xyz** [comment]
I,ve noticed the same error @jim3ma with the same version.

**Comment by jim3ma** [comment]
The first peer which back source is always CDN(if cdn is enabled).
@gaius-qi @244372610 Is there some details some the behaviour?

**Comment by mohafarooq** [comment]
Thank you, @jim3ma @gaius-qi @244372610, for your continued support. 
There are multiple issues it will lead us to. I will explain it one by one.

1. We cannot evaluate if the peers can serve pieces of images in v2. Currently, all the work is being done by CDN, and we don't know if the peers will do the work. Are there anyways to maintain the preferences? e.g. sourceOrder: peer,cdn,registry ? Can we force the pieces to come from peers so that we can evaluate them? 
2. The power of the peer is the aggregated/combined network throughput. Right now, all the pieces are served by the CDN. It is ok if a few of the pieces come from the CDN, but if v2 doesn't utilize the n/w bandwidth of the peers, we are leaving a lot on the table 
3. If we set up K8s to automatically scale up the CDN based on CDN network bandwidth usage, we will never utilize the peer network; instead, we will automatically increase the CDN count. 

Feel free to educate me if I am wrong.

**Comment by mohafarooq** [comment]
Changing the below configuration in scheduler.yaml made sure that the peer started to get download requests. The default configurations are too low (10m and 3m). What do TTL and TTI mean and what are the optimal settings?  

```
gc:
    # peerGCInterval peer's gc interval
    peerGCInterval: 1m
    # peerTTL peer's TTL duration
    peerTTL: 10h
    # peerTTI peer's TTI duration
    peerTTI: 3h
    # taskGCInterval task's gc interval
    taskGCInterval: 1m
    # taskTTL task's TTL duration
    taskTTL: 10h
    # taskTTI task's TTI duration
    taskTTI: 3h

```
