### ISSUE TITLE
dfget 拉起的 daemon 配置不生效

### ISSUE THREAD

**Issue by wciq1208** [dragonflyoss/Dragonfly2#874]
### Bug report:

dfget.yaml的路径：
/etc/dragonfly/dfget-daemon.yaml
/mnt/sdb1/dragonfly/config/dfget.yaml
内容都一致

dfget.yaml内容：
```
# daemon 存活时间, 设置为 0 秒时，daemon 将不会退出
# dfget daemon 可以由 dfget 拉起
aliveTime: 0s

# daemon gc 间隔
gcInterval: 1m0s

# daemon 数据目录
# linux 上默认目录为 $HOME/.dragonfly/dfget-daemon/
# macos(仅开发、测试), 默认目录是 /Users/$USER/.dragonfly/dfdaemon/
dataDir: /mnt/sdb1/dragonfly/data/

# daemon 工作目录
# linux 上默认目录 $HOME/.dragonfly/dfget-daemon/
# macos(仅开发、测试), 默认目录是 /Users/$USER/.dragonfly/dfdaemon/
workHome: /mnt/sdb1/dragonfly/data/

# 当 daemon 退出是, 是否保存缓存数据
# 保留缓存数据在升级 daemon 的时候比较有用
# 默认为 false
keepStorage: true

# 调度器地址
# 尽量使用同一个地区的调度器.
# daemon 将会根据 task id 来进行一致性 hash 来选择所有配置的调度器
scheduler:
  manager:
    # 通过 manager 接口动态获取 scheduler 列表
    enable: true
    # manager 服务地址
    netAddrs:
      - type: tcp
        addr: 127.0.0.1:65003
    # scheduler 列表刷新时间
    refreshInterval: 5m
  # 调度超时
  scheduleTimeout: 30s
  # 是否禁用回源，禁用回源后，在调度失败时不在 daemon 回源，直接返错
  disableAutoBackSource: true
  # 调度器地址实例
  netAddrs:
    - type: tcp
      addr: 127.0.0.1:8002

# 是否开启 verbose 日志模式
verbose: true

# 遥测配置
# jaeger 地址, 例如: http://jaeger.dragonfly.svc:14268/api/traces
jaeger: ""

# 用于注册到调度器的 daemon 信息
host:
  # 服务监听地址
  listenIP: 0.0.0.0
  # 访问 IP 地址
  # 其他 daemon 可以通过这个 IP 地址连接过来
  advertiseIP: 0.0.0.0
  # 地理信息, 通过 "|" 符号分隔
  location: ""
  # 机房信息
  idc: ""
  # 安全域信息，不同安全域之间网络隔离
  securityDomain: ""
  # 网络拓扑结构，通过 "|" 符号分隔
  netTopology: ""
  # 主机名称
  # hostname: ""

# 下载服务选项
download:
  # 是否计算文件摘要，设置为 false 的话，会节省内存
  calculateDigest: true
  # 总下载限速
  totalRateLimit: 200Mi
  # 单个任务下载限速
  perPeerRateLimit: 100Mi
  # 下载 GRPC 配置
  downloadGRPC:
    # 安全选项
    security:
      insecure: true
      cacert: ""
      cert: ""
      key: ""
      tlsConfig: null
    # 下载服务监听地址，dfget 下载文件将通过该地址连接到 daemon
    # 目前是支持 unix domain socket
    unixListen:
      # linux 上默认路径为 /var/run/dfdaemon.sock
      # macos(仅开发、测试), 默认目录是 /tmp/dfdaemon.sock
      socket: /var/run/dfdaemon.sock
  # peer grpc 选项
  # peer 之间通信和下载配置
  peerGRPC:
    security:
      insecure: true
      cacert: ""
      cert: ""
      key: ""
    tcpListen:
      # 监听地址
      listen: 0.0.0.0
      # 监听端口
      # 指定固定端口，也可以指定端口范围
      port: 65000
#     port:
#       start: 65000
#       end: 65009

# 上传服务选项
upload:
  # 上传限速
  rateLimit: 100Mi
  security:
    insecure: true
    cacert: ""
    cert: ""
    key: ""
  tcpListen:
    # 监听地址
    listen: 0.0.0.0
    # 监听端口
    # 指定固定端口，也可以指定端口范围
    port: 65002
#   port:
#     start: 65020
#     end: 65029

# peer task 存储选项
storage:
  # task data 过期时间
  # 超过指定时间没有访问之后，缓存数据将会被清理
  taskExpireTime: 3m0s
  # storage strategy when process task data
  # io.d7y.storage.v2.simple : download file to data directory first, then copy to output path, this is default action
  #                           the download file in date directory will be the peer data for uploading to other peers
  # io.d7y.storage.v2.advance: download file directly to output path with postfix, hard link to final output,
  #                            avoid copy to output path, fast than simple strategy, but:
  #                            the output file with postfix will be the peer data for uploading to other peers
  #                            when user delete or change this file, this peer data will be corrupted
  # default is io.d7y.storage.v2.advance
  strategy: io.d7y.storage.v2.advance
  # 磁盘 GC 阈值，缓存数据超过阈值后，最旧的缓存数据将会被清理
  diskGCThreshold: 50Gi
  # 相同 task id 的 peer task 是否复用缓存
  multiplex: true

# 代理服务配置文件，也可以使用下面的配置格式
# proxy: ""

# 代理服务详细选项
proxy:
  # 哈希 url 的时候的过滤选项
  # 例如：defaultFilter: "Expires&Signature":
  #  http://localhost/xyz?Expires=111&Signature=222 and http://localhost/xyz?Expires=333&Signature=999
  # 是相同的 task
  defaultFilter: "Expires&Signature"
  security:
    insecure: true
    cacert: ""
    cert: ""
    key: ""
  tcpListen:
    # 监听的网络命名空间, 例如：/proc/1/ns/net
    # 主要用在部署 kubernetes 中的时候，daemon 不使用 host network 时，监听宿主机的端口
    # 仅支持 Linux
    namespace: ""
    # 监听地址
    listen: 0.0.0.0
    # 监听端口
    port: 65001
  registryMirror:
    # 开启时，使用 header 里的 "X-Dragonfly-Registry" 替换 url 里的 host
    dynamic: true
    # 镜像中心地址
    url: https://index.docker.io
    # 忽略镜像中心证书错误
    insecure: true
    # 镜像中心证书
    certs: []
    # 是否直连镜像中心，true 的话，流量不再走 p2p
    direct: false

  proxies:
    # 代理镜像 blobs 信息
    - regx: blobs/sha256.*
    # 访问 some-registry 的时候，转换成 https 协议
    - regx: some-registry/
      useHTTPS: true
    # 直接透传流量，不走蜻蜓
    - regx: no-proxy-reg
      direct: true
    # 转发流量到指定地址
    - regx: some-registry
      redirect: another-registry

  hijackHTTPS:
    # https 劫持的证书和密钥
    # 建议自签 CA 并更新主机证书链
    cert: ""
    key: ""
    # 需要走蜻蜓 p2p 的流量
    hosts:
      - regx: mirror.aliyuncs.com:443 # 正则匹配
        # 忽略证书错误
        insecure: true
        # 可选：对端证书
        certs: []
  # 同时下载任务数, 0 代表不限制
  maxConcurrency: 0
  # 白名单，如果设置了，仅白名单内可以走代理，其他的都拒绝
  whiteList:
    # 主机信息
    - host: ""
      # 正则匹配
      regx:
      # 端口白名单
      ports:
      # - 80
      # - 443
```

dfget启动命令：
`
./dfget --home /mnt/sdb1/dragonfly/data --config /mnt/sdb1/dragonfly/config/dfget.yaml --url 'http://10.23.24.230:1234/000841_0' --console --show-progress -O test --limit 1K --notbacksource --totallimit 1K -n --verbose
`

daemon日志：
`
{"level":"info","ts":"2021-12-06 11:42:27.845","caller":"cmd/daemon.go:93","msg":"Version:\nMajor: 2, Minor: 0, GitVersion: v2.0.0, GitCommit: unknown, Platform: linux, BuildTime: unknown, GoVersion: unknown, Gotags: unknown, Gogcflags: unknown"}
{"level":"info","ts":"2021-12-06 11:42:27.847","caller":"cmd/daemon.go:140","msg":"daemon is launched by pid: 220812"}
{"level":"info","ts":"2021-12-06 11:42:27.849","caller":"cmd/daemon.go:144","msg":"client daemon configuration:\nconsole: false\nverbose: false\npprof-port: -1\njaeger: \"\"\nservice-name: dragonfly-dfget\naliveTime:\n    duration: 5m0s\ngcInterval:\n    duration: 1m0s\ndataDir: /home/wciq1208/.dragonfly/dfget-daemon/\nworkHome: /home/wciq1208/.dragonfly/dfget-daemon/\nkeepStorage: false\nscheduler:\n    manager:\n        enable: false\n        netAddrs: []\n        refreshInterval: 5m0s\n    netAddrs:\n        - type: tcp\n          addr: 127.0.0.1:8002\n    scheduleTimeout:\n        duration: 5m0s\n    disableAutoBackSource: false\nhost:\n    securityDomain: \"\"\n    location: \"\"\n    idc: \"\"\n    netTopology: \"\"\n    hostname: wciq1208-HP-288-Pro-G3-MT\n    listenIP: 0.0.0.0\n    advertiseIP: 10.23.24.230\ndownload:\n    totalRateLimit:\n        limit: 1.048576e+08\n    perPeerRateLimit:\n        limit: 2.097152e+07\n    pieceDownloadTimeout: 30s\n    downloadGRPC:\n        security:\n            insecure: true\n            caCert: \"\"\n            cert: \"\"\n            key: \"\"\n            tlsConfig: null\n        unixListen:\n            socket: /var/run/dfdaemon.sock\n    peerGRPC:\n        security:\n            insecure: true\n            caCert: \"\"\n            cert: \"\"\n            key: \"\"\n            tlsConfig: null\n        tcpListen:\n            listen: \"\"\n            port:\n                start: 65000\n                end: 65535\n            namespace: \"\"\n    calculateDigest: true\nproxy:\n    security:\n        insecure: true\n        caCert: \"\"\n        cert: \"\"\n        key: \"\"\n        tlsConfig: null\n    tcpListen:\n        listen: 0.0.0.0\n        port:\n            start: 0\n            end: 0\n        namespace: \"\"\n    basicAuth: null\n    defaultFilter: \"\"\n    maxConcurrency: 0\n    registryMirror: null\n    whiteList: []\n    proxies: []\n    hijackHTTPS: null\n    dumpHTTPContent: false\nupload:\n    security:\n        insecure: true\n        caCert: \"\"\n        cert: \"\"\n        key: \"\"\n        tlsConfig: null\n    tcpListen:\n        listen: 0.0.0.0\n        port:\n            start: 65002\n            end: 65535\n        namespace: \"\"\n    rateLimit:\n        limit: 1.048576e+08\nstorage:\n    dataPath: \"\"\n    taskExpireTime:\n        duration: 3m0s\n    diskGCThreshold: 0.0B\n    multiplex: false\n    strategy: io.d7y.storage.v2.advance\nconfigServer: \"\"\n"}
{"level":"info","ts":"2021-12-06 11:42:27.849","caller":"client/client.go:46","msg":"scheduler server list: [dns:///127.0.0.1:8002]"}
{"level":"info","ts":"2021-12-06 11:42:27.849","caller":"peer/piece_manager.go:74","msg":"set calculateDigest to true for piece manager"}
{"level":"info","ts":"2021-12-06 11:42:27.850","caller":"daemon/daemon.go:364","msg":"serve download grpc at unix:///usr/local/dragonfly/daemon.sock"}
{"level":"info","ts":"2021-12-06 11:42:27.850","caller":"daemon/daemon.go:375","msg":"serve peer grpc at tcp://[::]:65000"}
{"level":"info","ts":"2021-12-06 11:42:27.850","caller":"daemon/daemon.go:432","msg":"serve upload service at tcp://[::]:65002"}
`

### Expected behavior:

Dragonfly2-2.0.1-rc.8-linux-amd64.tar.gz

### How to reproduce it:

可稳定复现

### Environment:
- Dragonfly version:Dragonfly2-2.0.1-rc.8
- OS:linux
- Kernel (e.g. `uname -a`):5.15.0-051500-generic
- Others:ubuntu 20.04
