### ISSUE TITLE
Proxies not honored when proxying something else than docker registry

### ISSUE THREAD

**Issue by momiji** [dragonflyoss/Dragonfly2#959]
### Bug report:

When proxying something else than a docker registry, like a yum repository, I found that dfdaemon is always doing direct request to source, whatever I set in the proxies list.

My partial settings looks like:
```
registryMirror:
  url: https://my-yum-repository.my-domain.com
proxies:
- regx: .*
```

### Expected behavior:

All download should honor proxies list and in my case match .* and therefore should be cached by dfdaemon.

Once this is resolved, I think the documentation may reflect different patterns to follow, assuming the regex is not a full match (otherwise we need to add a few `.*`):

- for docker registries, cache only image layers:
  ```
  proxies:
  - regx: /blobs/sha256:
  ```
- for yum registries, cache everything except repomd.xml:
  ```
  proxies:
  - regx: /repomd.xml
    direct: true
  - regx: .*
  ```

### My understanding and comments so far - I may be completely wrong, if so I apologize...

0. This is projet is wow... I love it!

1. I'm not sure to have fully understand how the dfdaemon works.

At first I thought it could work as a proxy for downloading things. For example, if I use `curl --proxy dfdaemon:dfport URL`, but it never cached anything, and I finally guess it is not the way it is supposed to work. I wonder is this is something by design (and in that case why is it working when used that way?), or is it just an unexpected behaviour.

In that last case, I would hardly suggest to allow use of dfdaemon as a proxy (as a new feature), but only allow it to work when the host matches the registryMirror set in the configuration. What I mean is `curl -x fdip:fdport https://registryMirror/...` behaves the same as `curl http://fdip:fdport/...`. Of course, this may removes any need for dfget, but I haven't used it yet so I don"t reaaly know what it can do or should be used for.

Then I went to use `curl http://dfip:dfport/...` to be able to use dfdaemon correctly, however it still don't do any caching in dfdaemon.

Finally I found the url need to contain `blobs/sha256` in the URL to have cache working.

My assumption here is this is related to this code, that uses hard coded regex instead of using proxies list: https://github.com/dragonflyoss/Dragonfly2/blob/464da9fe3de5e34c0a48a31a1f6237b037556069/client/daemon/transport/transport.go#L42-L45
https://github.com/dragonflyoss/Dragonfly2/blob/464da9fe3de5e34c0a48a31a1f6237b037556069/client/daemon/transport/transport.go#L168-L172

2. I didn't understand what `whiteList` was for, Maybe a small paragraph could be added in the documentation to explain how it works.

And the code looks a bit weird to me: https://github.com/dragonflyoss/Dragonfly2/blob/9dca7ee1e411420dd1d1dd33dce67fa4b1be2922/client/daemon/proxy/proxy.go#L506
Shouldn't it be more like this:
```
if (v.Host == "" || v.Host == host) && (v.Regx == nil || v.Regx.MatchString(host)) {
```

### Environment:
- Dragonfly version: 2.0.1
- OS: official docker images, running on redhat 7.9
- Kernel (e.g. `uname -a`):
- Others:

**Comment by jim3ma** [comment]
1. mirror is always for docker registry now. We can provide a regex for customize the url which need process by dragonfly.
2. `whiteList` is a filter for which domains dragonfly can served. It will be block all request which is not in `whiteList`.

**Comment by jim3ma** [comment]
@momiji Can you search logs in `/var/log/dragonfly/daemon/core.log` with `round trip` ?

**Comment by momiji** [comment]
I think making it working with something else than a docker registry can be very helpfull to many people (if not a huge improvement), and that will definitely increase the usage of dragonfly to much much more than only registry mirrors...

If using as a registryMirror, I can see the `round trip` when url contains `blobs/sha256`:
```
2021-12-27T08:48:09.391Z        DEBUG   transport/transport.go:152      round trip with dragonfly: https://xxx/repos/blobs/sha256:x/rpm2/rhel-8-for-x86_64-baseos-rpms-8/Packages/k/kernel-core-4.18.0-348.el8.x86_64.rpm
2021-12-27T08:48:09.392Z        INFO    transport/transport.go:179      start download with url: https://xxx/repos/blobs/sha256:x/rpm2/rhel-8-for-x86_64-baseos-rpms-8/Packages/k/kernel-core-4.18.0-348.el8.x86_64.rpm       {"peer": "184.6.133.121-1-e2051aa3-88ab-4d4a-92f9-486b6ac0136f", "component": "transport"}
2021-12-27T08:48:09.392Z        INFO    peer/peertask_reuse.go:115      reuse from peer task: 184.6.133.121-1-9113707b-a415-405e-a586-489190ea74bf, size: 39380632      {"peer": "184.6.133.121-1-e2051aa3-88ab-4d4a-92f9-486b6ac0136f", "task": "9f803587ca255975eced626edca12d6340ce93a2303e7a823f3b528f25a1559b", "component": "reuseStreamPeerTask"}
2021-12-27T08:48:09.392Z        DEBUG   clientutil/keepalive.go:48      update storage manager keepalive access time: 2021-12-27T08:48:09Z
2021-12-27T08:48:09.392Z        INFO    transport/transport.go:223      download stream attribute: map[Content-Length:[39380632] X-Dragonfly-Peer:[184.6.133.121-1-e2051aa3-88ab-4d4a-92f9-486b6ac0136f] X-Dragonfly-Task:[9f803587ca255975eced626edca12d6340ce93a2303e7a823f3b528f25a1559b]]  {"peer": "184.6.133.121-1-e2051aa3-88ab-4d4a-92f9-486b6ac0136f", "component": "transport"}
```

However without `blobs/sha256`:
```
2021-12-27T08:49:50.032Z        DEBUG   transport/transport.go:155      round trip directly, method: GET, url: https://xxx/repos/rpm2/rhel-8-for-x86_64-baseos-rpms-8/Packages/k/kernel-core-4.18.0-348.el8.x86_64.rpm
```

Anyway, if using as an http proxy, there is no `round trip` in the logs:
```
2021-12-27T08:43:59.088Z        DEBUG   proxy/proxy.go:347      proxy cert is not configured, tunneling https request for xxx:443
2021/12/27 08:44:05 http: response.WriteHeader on hijacked connection from d7y.io/dragonfly/v2/client/daemon/proxy.tunnelHTTPS (proxy.go:579)
2021/12/27 08:44:05 http: response.Write on hijacked connection from fmt.Fprintln (print.go:265)
```

**Some thoughts**

I'm not an expert in docker registries so far, but it looks like to me that a docker registry may be configured as a proxy, except that configuring client to use a proxy for specific registries is not possible (it is a global flag), hence the need to have the registry being accessed directly and not as an http proxy (registryMirror configuration). I believe this problem is the same for yum repositories, as it is not possible to configure proxy per repository.

That being stated, I suspect proxies and registryMirror should be exactly the the same:
- when accessed directly, we need to compute the target url to serve.
  This is done today by the registryMirror, that can be enhanced to several mirrors, based on a regex or with the `X-Dragonfly-Registry` header.
- when accesed as an http proxy: we already know the target url to server.

Once the target url is computed:
- whiteList is used to limit the usage of dragonfly, based on the host of the target url
- proxies define how the requetss are handled (direct/redirect/useHTTPS)
  Once caching is implemented in the proxy part, we could disable it with direct=true, and block some requests byt setting redirect value to a dummy one.

To explain my point, as my english is not as fluent as I would want, we may change the configuration to something like this:
```
# define how requests are proxied when http request is directly calling dragonfly (not as an http proxy)
# once the target host is identified, the proxies configuration is used to specify how to handle the request
direct:
  # when enable, using header "X-Dragonfly-Registry" for remote instead of url
  dynamic: true
  mirrors:
  # mirror default configuration is:
  # - regex: .*         # regx is fully matched (^ and $ are automatically applied), and tested againt the query starting by / (just after http://host:port)
  #   insecure: false   # use true to disable https certificate check
  #   certs: []         # certs to check the certificate in case of private CA or self-seigned certificates, when insecure = false
  #   direct: false     # use true to disable cache
  # to configure one single mirror:
  # - regx: .*
  #   host: https://my-registry-mirror
  # to configure several mirrors, based on the first query item, () are use to remove it from the url:
  # - regx: /(my-registry-mirror/).*
  #   host: https://my-registry-mirror
  # - regx: /(my-yum-mirror/).*
  #   host: http://my-yum-mirror

# define how requests are proxied when http request is proxied through dragonfly
proxies:
  # proxy default configuration is:
  # - regx: .*          # regex is fully matched (^ and $ are automatically applied), and tested against the full url
  #   direct: false     # use tru to disable caching
  #   redirect:         # use a enon empty value to change the target host, use a dummy ip to block request
  #   useHTTPS: false   # use true to upgrade the request to HTTPS, when dragonfly is in HTTP but the target is HTTPS
  # for a registry mirror, we need to cache /blobs/sha256: urls
  # - regx: https://my-registry-mirror/.*/blobs/sha256:.*
  # - regx: https://my-reigstry-mirror/.*
  #   direct: true
  # for a yum reposiroty mirror, we need to cache .* except for repomd.xml
  # - regx: https://my-yum-mirror/.*/repomd.xml
  #   direct: true
  # - regx: https://my-yum-mirror/.*
  #   direct: true
```

If this make sense to the team, I think this can be done in two steps:
- fix proxies caching and go through proxies configuration when accessed directly (registryMirror) - this will solve the issue for mirrors other than docker registries
- replace registryMirror with multiple mirrors

Finally, I checked again the whiteList part and I was wrong, it's fine as it is.

**Comment by momiji** [comment]
I looked a little bit omre at the project, have been able to install it on WSL2, and run e2e-test (but it failed, no luck).

However, now that I have a way to rebuild the projet, I opened it in idea and it seems to me that the only thing to change is this line:
```
func (proxy *Proxy) shouldUseDragonflyForMirror(req *http.Request) bool {
	return proxy.registry != nil && !proxy.registry.Direct && proxy.shouldUseDragonfly(req)
}
```
to this:
```
	return proxy.registry != nil && !proxy.registry.Direct && proxy.shouldUseDragonfly(req)
```

The tests in proxy_test should probably be updated as well, of course :)

**Comment by jim3ma** [comment]
> I looked a little bit omre at the project, have been able to install it on WSL2, and run e2e-test (but it failed, no luck).
> 
> However, now that I have a way to rebuild the projet, I opened it in idea and it seems to me that the only thing to change is this method:
> 
> ```
> func (proxy *Proxy) shouldUseDragonflyForMirror(req *http.Request) bool {
> 	return proxy.registry != nil && !proxy.registry.Direct && transport.NeedUseDragonfly(req)
> }
> ```
> 
> to this:
> 
> ```
> func (proxy *Proxy) shouldUseDragonflyForMirror(req *http.Request) bool {
> 	return proxy.registry != nil && !proxy.registry.Direct && proxy.shouldUseDragonfly(req)
> }
> ```
> 
> The tests in proxy_test.go should probably be updated as well, of course :)

`proxy.shouldUseDragonfly(req)` is used to check proxy rules in `proxy.proxies`, not the mirror.

In my opinion, the following configuration will be okay to implement.

```
direct:
  dynamic: true
  mirrors:
  - regex: .*
     insecure: false
     certs: []
     direct: false
     redirect: 127.0.0.1
     useHTTPS: false
```

**Comment by momiji** [comment]
I was thinking of preventing as much as possible breaking changes for end-users, and feel that what I proposed was giong to break too much things:
- don't break registryMirror feature by going thourgh proxies that may not have been configured with blobs/sha256 regex
- don't duplicate proxies list as it will most probably contain the exact same content - I can't find any reason why it shouldn't

In that case, I propose something more easy to upgrade:
- to allow usage of proxies for registries, add a new `useProxies: false` in registryMirror part
- to allow dynamic mirrors based on regex in addition to the header, add a new mirror section

```
  registryMirror:
    # default mirror configuration
    dynamic: true
    url: https://index.docker.io
    insecure: true
    certs: []
    direct: false
    useProxies: false                  # when enabled, use proxies instead of default regex blobs/sha256.* to decide whether to use dragonfly for downloading
    
    # additionnal mirrors can be added, in place of default if one matches
    mirrors:
    - regx: ^/my-host/(.*)
      url: https://another-host/$1     # this is like apache way to configure proxies
      insecure: false
      certs: []
      direct: false
      redirect:
      useProxies: true
    
  proxies:
    - regx: blobs/sha256
```

I feel this is much better:
- using proxies for registries is optional, hence not breaking existing configuration and only serves for yum mirrors and so on
- using additionnal mirrors configuration solves the problem of converting existing registryMirror configuration to a mirrors list, as well as having a default configuration in case no regex matches
- using apache way to configure mirror is something everybody is used for a long time now
- it is still needed to check proxies regex to the full url, I didn't check the code yet

I team agrees, maybe this can be split in to features, the first one with `useProxies` (more urgent IMHO) and the second one with the mirrors list (less important).

**Comment by momiji** [comment]
I'm welcome to discuss on the PR #963

**Comment by jim3ma** [comment]
> I was thinking of preventing as much as possible breaking changes for end-users, and feel that what I proposed was giong to break too much things:
> 
> * don't break registryMirror feature by going thourgh proxies that may not have been configured with blobs/sha256 regex
> * don't duplicate proxies list as it will most probably contain the exact same content - I can't find any reason why it shouldn't
> 
> In that case, I propose something more easy to upgrade:
> 
> * to allow usage of proxies for registries, add a new `useProxies: false` in registryMirror part
> * to allow dynamic mirrors based on regex in addition to the header, add a new `mirrors` section
> 
> ```
>   registryMirror:
>     # default mirror configuration
>     dynamic: true
>     url: https://index.docker.io
>     insecure: true
>     certs: []
>     direct: false
>     useProxies: false                  # when enabled, use proxies instead of default regex blobs/sha256.* to decide whether to use dragonfly for downloading
>     
>     # additionnal mirrors can be added, in place of default if one matches
>     mirrors:
>     - regx: ^/my-host/(.*)
>       url: https://another-host/$1     # this is like apache way to configure proxies
>       insecure: false
>       certs: []
>       direct: false
>       redirect:
>       useProxies: true
>     
>   proxies:
>     - regx: blobs/sha256
> ```
> 
> I feel this is much better:
> 
> * using proxies for registries is optional, hence not breaking existing configuration and only serves for yum mirrors and so on
> * using additionnal mirrors configuration solves the problem of converting existing registryMirror configuration to a mirrors list, as well as having a default configuration in case no regex matches
> * using apache way to configure mirror is something everybody is used for a long time now
> * it is still needed to check proxies regex to the full url, I didn't check the code yet
> 
> If team agrees, maybe this can be split in two features, the first one with `useProxies` (more urgent IMHO) and the second one with the mirrors list (less important).

LGTM

**Comment by momiji** [comment]
I wrote the second feature also, however I found it too complex to add all flags in mirror, as most of them are used on transport creation and not dynamically on each call (which is more efficient of course).

Implemented config is:
```
  registryMirror:
    # default mirror configuration
    dynamic: true
    url: https://index.docker.io
    insecure: true
    certs: []
    direct: false
    useProxies: false                  # when enabled, use proxies instead of default regex blobs/sha256.* to decide whether to use dragonfly for downloading
    
    # additionnal mirrors can be added, in place of default if one matches
    mirrors:
    - regx: ^/my-host/(.*)
      url: https://another-host/$1     # this is like apache way to configure proxies
    
  proxies:
    - regx: blobs/sha256
```

If it is OK with you, should I add the commit to the PR or wait for first PR to be injected before creating a new one?
If you want to take a look, commit is here: https://github.com/momiji/Dragonfly2/commit/fbf91ac93394c0e2540c21948a52edb0bf7677e2

**Comment by jim3ma** [comment]
The PR #965 has been merged. Can add a document to describe this feature in https://github.com/dragonflyoss/Dragonfly2/tree/main/docs/en/deployment ?

**Comment by momiji** [comment]
I'll have a look to how to explain use case, but my english skill is as bad as my PR skills :)

**Comment by momiji** [comment]
Regarding mirrors, I think my proposal is wrong.
Url rewriting can be used for both direct and proxy mode, and is already present in proxy mode with the `redirect` flag.

I think the best thing would be to enhance `redirect` to accept urls in addition to hostnames, when containing a `/`, like this:
```
proxies:
# existing sample
- regx: some-registry                     # warn: the regex matches anywhere in the url and not only hostname
  redirect: another-registry              # no /, this is the new hostname
  useHTTPS: true
# a more exact way to do it could be
- regx: ^http://some-registry/            # this is the good regex to use
  redirect: another-registry              # no /, this is the new hostname
  useHTTPS: true
# a more generalitic way to do it could be, no more need to add useHTTPS here
- regx: ^http://some-registry/(.*)        # this is the regex to use, with group extraction like apache ProxyPass directive
  redirect: https://another-registry/$1   # with /, this is the new URL with regex replacement
```

This way it is less redundant with adding a `mirrors` section and works globally!

A PR will follow soon for this one :)
